name: build docker image

on:
    push:
        branches-ignore: 
            - main

jobs:
    open-pr:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Make pr.sh executable
          run: chmod +x ./pr.sh

        - name: Run pr.sh (non main only)
          if: github.ref != 'refs/heads/main'
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            GITHUB_HEAD_REF: ${{ github.head_ref }}
            GITHUB_REF_NAME: ${{ github.ref_name }}
          run: ./pr.sh