name: build docker image

on:
    push:
        branches-ignore: 
            - main
        paths-ignore:
            - 'version'

jobs:
    open-pr:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Make poll request script executable
          run: chmod +x ./pr.sh

        - name: invokes pull request if the branch is not main
          if: github.ref != 'refs/heads/main'
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            GITHUB_HEAD_REF: ${{ github.head_ref }}
            GITHUB_REF_NAME: ${{ github.ref_name }}
          run: ./pr.sh